[web]
  title="RedwoodJS Auth Playground"
  port = 8910
  apiProxyPath = "/.netlify/functions"
  includeEnvironmentVariables = [
    'AUTH0_DOMAIN',
    'AUTH0_CLIENT_ID',
    'AUTH0_REDIRECT_URI',
    'AUTH0_AUDIENCE',
    'AZURE_ACTIVE_DIRECTORY_CLIENT_ID',
    'AZURE_ACTIVE_DIRECTORY_AUTHORITY',
    'AZURE_ACTIVE_DIRECTORY_REDIRECT_URI',
    'AZURE_ACTIVE_DIRECTORY_LOGOUT_REDIRECT_URI',
    'MAGICLINK_PUBLIC',
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_DATABASE_URL',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
    'SUPABASE_KEY',
    'SUPABASE_URL',
    'SUPABASE_JWT_SECRET',
    'NHOST_BACKEND_URL',
    'NHOST_JWT_SECRET',
  ]
[api]
  port = 8911
  schemaPath = "./api/db/schema.prisma"
[browser]
  open = true
[experimental]
  esbuild = false
  useEnvelop = true
